[package]
name = "emporion-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "2.2.0"
cosmwasm-std = "2.2.0"
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"

[features]
library = []

[dev-dependencies]
cw-multi-test = "2.3.1"
