/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Decimal, Uint64, Uint128, InstantiateMsg, BankDistribution, ExecuteMsg, CreateProductMsg, CreateBulkProductsMsg, UpdateProductMsg, UpdateBulkProductMsg, CreateOrderMsg, OrderForSeller, AcceptOrderMsg, CancelOrderMsg, CompleteOrderMsg, DisputeOrderMsg, RateUserMsg, DistributeMsg, UpdateParamsMsg, QueryMsg, Empty, ByIndex, Paginated, PaginatedByAddress, PaginatedByIndex, GetByAddress, MigrateMsg, Bank, Mark, Addr, OrderStatus, Order, Params, Product, Rating, ArrayOfOrder, ArrayOfProduct, ArrayOfRating } from "./Emporion.types";
export interface EmporionReadOnlyInterface {
  contractAddress: string;
  getParams: () => Promise<Params>;
  getDistribution: () => Promise<Bank>;
  getProduct: ({
    id
  }: {
    id: Uint64;
  }) => Promise<Product>;
  listAllProducts: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }) => Promise<ArrayOfProduct>;
  listProductsFromUser: ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }) => Promise<ArrayOfProduct>;
  getOrder: ({
    id
  }: {
    id: Uint64;
  }) => Promise<Order>;
  listAllOrders: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }) => Promise<ArrayOfOrder>;
  listOrdersForUser: ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }) => Promise<ArrayOfOrder>;
  listOrdersFromUser: ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }) => Promise<ArrayOfOrder>;
  getRating: ({
    id
  }: {
    id: Uint64;
  }) => Promise<Rating>;
  listAllRatings: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }) => Promise<ArrayOfRating>;
  listRatingsForUser: ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }) => Promise<ArrayOfRating>;
  listRatingsFromUser: ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }) => Promise<ArrayOfRating>;
  listRatingsByOrder: ({
    id,
    pagination
  }: {
    id: Uint64;
    pagination: Paginated;
  }) => Promise<ArrayOfRating>;
  getMark: ({
    addr
  }: {
    addr: string;
  }) => Promise<Mark>;
}
export class EmporionQueryClient implements EmporionReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getParams = this.getParams.bind(this);
    this.getDistribution = this.getDistribution.bind(this);
    this.getProduct = this.getProduct.bind(this);
    this.listAllProducts = this.listAllProducts.bind(this);
    this.listProductsFromUser = this.listProductsFromUser.bind(this);
    this.getOrder = this.getOrder.bind(this);
    this.listAllOrders = this.listAllOrders.bind(this);
    this.listOrdersForUser = this.listOrdersForUser.bind(this);
    this.listOrdersFromUser = this.listOrdersFromUser.bind(this);
    this.getRating = this.getRating.bind(this);
    this.listAllRatings = this.listAllRatings.bind(this);
    this.listRatingsForUser = this.listRatingsForUser.bind(this);
    this.listRatingsFromUser = this.listRatingsFromUser.bind(this);
    this.listRatingsByOrder = this.listRatingsByOrder.bind(this);
    this.getMark = this.getMark.bind(this);
  }
  getParams = async (): Promise<Params> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_params: {}
    });
  };
  getDistribution = async (): Promise<Bank> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_distribution: {}
    });
  };
  getProduct = async ({
    id
  }: {
    id: Uint64;
  }): Promise<Product> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_product: {
        id
      }
    });
  };
  listAllProducts = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }): Promise<ArrayOfProduct> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_all_products: {
        limit,
        start_after: startAfter
      }
    });
  };
  listProductsFromUser = async ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }): Promise<ArrayOfProduct> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_products_from_user: {
        addr,
        pagination
      }
    });
  };
  getOrder = async ({
    id
  }: {
    id: Uint64;
  }): Promise<Order> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_order: {
        id
      }
    });
  };
  listAllOrders = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }): Promise<ArrayOfOrder> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_all_orders: {
        limit,
        start_after: startAfter
      }
    });
  };
  listOrdersForUser = async ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }): Promise<ArrayOfOrder> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_orders_for_user: {
        addr,
        pagination
      }
    });
  };
  listOrdersFromUser = async ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }): Promise<ArrayOfOrder> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_orders_from_user: {
        addr,
        pagination
      }
    });
  };
  getRating = async ({
    id
  }: {
    id: Uint64;
  }): Promise<Rating> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_rating: {
        id
      }
    });
  };
  listAllRatings = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }): Promise<ArrayOfRating> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_all_ratings: {
        limit,
        start_after: startAfter
      }
    });
  };
  listRatingsForUser = async ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }): Promise<ArrayOfRating> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_ratings_for_user: {
        addr,
        pagination
      }
    });
  };
  listRatingsFromUser = async ({
    addr,
    pagination
  }: {
    addr: string;
    pagination: Paginated;
  }): Promise<ArrayOfRating> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_ratings_from_user: {
        addr,
        pagination
      }
    });
  };
  listRatingsByOrder = async ({
    id,
    pagination
  }: {
    id: Uint64;
    pagination: Paginated;
  }): Promise<ArrayOfRating> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_ratings_by_order: {
        id,
        pagination
      }
    });
  };
  getMark = async ({
    addr
  }: {
    addr: string;
  }): Promise<Mark> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_mark: {
        addr
      }
    });
  };
}
export interface EmporionInterface extends EmporionReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createProduct: ({
    listed,
    metaDataUrl,
    price
  }: {
    listed: boolean;
    metaDataUrl: string;
    price: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  createBulkProducts: ({
    products
  }: {
    products: CreateProductMsg[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  updateProduct: ({
    listed,
    metaDataUrl,
    price,
    productId
  }: {
    listed?: boolean;
    metaDataUrl?: string;
    price?: Uint128;
    productId: Uint64;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  updateBulkProduct: ({
    products
  }: {
    products: UpdateProductMsg[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  createOrder: ({
    orders
  }: {
    orders: OrderForSeller[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  acceptOrder: ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  cancelOrder: ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  completeOrder: ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  disputeOrder: ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  upsertRating: ({
    comment,
    mark,
    orderId,
    user
  }: {
    comment: string;
    mark: number;
    orderId: Uint64;
    user: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  distribute: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  updateParams: ({
    admin,
    distribution,
    platformFee,
    publishFee,
    rewardsDistributionAddress
  }: {
    admin?: string;
    distribution?: BankDistribution;
    platformFee?: Decimal;
    publishFee?: Uint128;
    rewardsDistributionAddress?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class EmporionClient extends EmporionQueryClient implements EmporionInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createProduct = this.createProduct.bind(this);
    this.createBulkProducts = this.createBulkProducts.bind(this);
    this.updateProduct = this.updateProduct.bind(this);
    this.updateBulkProduct = this.updateBulkProduct.bind(this);
    this.createOrder = this.createOrder.bind(this);
    this.acceptOrder = this.acceptOrder.bind(this);
    this.cancelOrder = this.cancelOrder.bind(this);
    this.completeOrder = this.completeOrder.bind(this);
    this.disputeOrder = this.disputeOrder.bind(this);
    this.upsertRating = this.upsertRating.bind(this);
    this.distribute = this.distribute.bind(this);
    this.updateParams = this.updateParams.bind(this);
  }
  createProduct = async ({
    listed,
    metaDataUrl,
    price
  }: {
    listed: boolean;
    metaDataUrl: string;
    price: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_product: {
        listed,
        meta_data_url: metaDataUrl,
        price
      }
    }, fee_, memo_, funds_);
  };
  createBulkProducts = async ({
    products
  }: {
    products: CreateProductMsg[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_bulk_products: {
        products
      }
    }, fee_, memo_, funds_);
  };
  updateProduct = async ({
    listed,
    metaDataUrl,
    price,
    productId
  }: {
    listed?: boolean;
    metaDataUrl?: string;
    price?: Uint128;
    productId: Uint64;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_product: {
        listed,
        meta_data_url: metaDataUrl,
        price,
        product_id: productId
      }
    }, fee_, memo_, funds_);
  };
  updateBulkProduct = async ({
    products
  }: {
    products: UpdateProductMsg[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_bulk_product: {
        products
      }
    }, fee_, memo_, funds_);
  };
  createOrder = async ({
    orders
  }: {
    orders: OrderForSeller[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_order: {
        orders
      }
    }, fee_, memo_, funds_);
  };
  acceptOrder = async ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      accept_order: {
        order_id: orderId
      }
    }, fee_, memo_, funds_);
  };
  cancelOrder = async ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_order: {
        order_id: orderId
      }
    }, fee_, memo_, funds_);
  };
  completeOrder = async ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      complete_order: {
        order_id: orderId
      }
    }, fee_, memo_, funds_);
  };
  disputeOrder = async ({
    orderId
  }: {
    orderId: Uint64;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      dispute_order: {
        order_id: orderId
      }
    }, fee_, memo_, funds_);
  };
  upsertRating = async ({
    comment,
    mark,
    orderId,
    user
  }: {
    comment: string;
    mark: number;
    orderId: Uint64;
    user: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      upsert_rating: {
        comment,
        mark,
        order_id: orderId,
        user
      }
    }, fee_, memo_, funds_);
  };
  distribute = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      distribute: {}
    }, fee_, memo_, funds_);
  };
  updateParams = async ({
    admin,
    distribution,
    platformFee,
    publishFee,
    rewardsDistributionAddress
  }: {
    admin?: string;
    distribution?: BankDistribution;
    platformFee?: Decimal;
    publishFee?: Uint128;
    rewardsDistributionAddress?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_params: {
        admin,
        distribution,
        platform_fee: platformFee,
        publish_fee: publishFee,
        rewards_distribution_address: rewardsDistributionAddress
      }
    }, fee_, memo_, funds_);
  };
}