/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Uint64 = string;
export type Uint128 = string;
export interface InstantiateMsg {
  accepted_denom: string;
  distribution: BankDistribution;
  fund_id: Uint64;
  platform_fee: Decimal;
  publish_fee: Uint128;
  rewards_distribution_address: string;
}
export interface BankDistribution {
  rewards: Decimal;
  rnd: Decimal;
}
export type ExecuteMsg = {
  create_product: CreateProductMsg;
} | {
  create_bulk_products: CreateBulkProductsMsg;
} | {
  update_product: UpdateProductMsg;
} | {
  update_bulk_product: UpdateBulkProductMsg;
} | {
  create_order: CreateOrderMsg;
} | {
  accept_order: AcceptOrderMsg;
} | {
  cancel_order: CancelOrderMsg;
} | {
  complete_order: CompleteOrderMsg;
} | {
  dispute_order: DisputeOrderMsg;
} | {
  upsert_rating: RateUserMsg;
} | {
  distribute: DistributeMsg;
} | {
  update_params: UpdateParamsMsg;
};
export interface CreateProductMsg {
  listed: boolean;
  meta_data_url: string;
  price: Uint128;
}
export interface CreateBulkProductsMsg {
  products: CreateProductMsg[];
}
export interface UpdateProductMsg {
  listed?: boolean | null;
  meta_data_url?: string | null;
  price?: Uint128 | null;
  product_id: Uint64;
}
export interface UpdateBulkProductMsg {
  products: UpdateProductMsg[];
}
export interface CreateOrderMsg {
  orders: OrderForSeller[];
}
export interface OrderForSeller {
  loss_distribution_ratio: Decimal;
  product_ids: Uint64[];
}
export interface AcceptOrderMsg {
  order_id: Uint64;
}
export interface CancelOrderMsg {
  order_id: Uint64;
}
export interface CompleteOrderMsg {
  order_id: Uint64;
}
export interface DisputeOrderMsg {
  order_id: Uint64;
}
export interface RateUserMsg {
  comment: string;
  mark: number;
  order_id: Uint64;
  user: string;
}
export interface DistributeMsg {}
export interface UpdateParamsMsg {
  admin?: string | null;
  distribution?: BankDistribution | null;
  platform_fee?: Decimal | null;
  publish_fee?: Uint128 | null;
  rewards_distribution_address?: string | null;
}
export type QueryMsg = {
  get_params: Empty;
} | {
  get_distribution: Empty;
} | {
  get_product: ByIndex;
} | {
  list_all_products: Paginated;
} | {
  list_products_from_user: PaginatedByAddress;
} | {
  get_order: ByIndex;
} | {
  list_all_orders: Paginated;
} | {
  list_orders_for_user: PaginatedByAddress;
} | {
  list_orders_from_user: PaginatedByAddress;
} | {
  get_rating: ByIndex;
} | {
  list_all_ratings: Paginated;
} | {
  list_ratings_for_user: PaginatedByAddress;
} | {
  list_ratings_from_user: PaginatedByAddress;
} | {
  list_ratings_by_order: PaginatedByIndex;
};
export interface Empty {}
export interface ByIndex {
  id: Uint64;
}
export interface Paginated {
  limit?: number | null;
  start_after?: Uint64 | null;
}
export interface PaginatedByAddress {
  addr: string;
  pagination: Paginated;
}
export interface PaginatedByIndex {
  id: Uint64;
  pagination: Paginated;
}
export interface MigrateMsg {}
export interface Bank {
  rewards: Uint128;
  rnd: Uint128;
}
export type Addr = string;
export type OrderStatus = "pending" | "accepted" | "cancelled" | "completed" | "disputed";
export interface Order {
  buyer: Addr;
  cart: Uint64[];
  completed_at?: Uint64 | null;
  created_at: Uint64;
  id: Uint64;
  loss_distribution_ratio: Decimal;
  seller: Addr;
  status: OrderStatus;
  total: Uint128;
}
export interface Params {
  accepted_denom: string;
  admin: Addr;
  distribution: BankDistribution;
  fund_id: number;
  platform_fee: Decimal;
  publish_fee: Uint128;
  rewards_distribution_address: Addr;
}
export interface Product {
  created_at: Uint64;
  id: Uint64;
  last_updated_at?: Uint64 | null;
  listed: boolean;
  meta_data_url: string;
  owner: Addr;
  price: Uint128;
}
export interface Rating {
  comment: string;
  created_at: Uint64;
  id: Uint64;
  last_updated_at?: Uint64 | null;
  mark: number;
  order_id: Uint64;
  rated: Addr;
  rater: Addr;
}
export type ArrayOfOrder = Order[];
export type ArrayOfProduct = Product[];
export type ArrayOfRating = Rating[];